export KD_PROJECT_ROOT_DIRECTORY=$(cd $(dirname "$KD_SCRIPT_VARS_FILE")/..; pwd)

export KD_SCRIPTS_DIRECTORY=$KD_PROJECT_ROOT_DIRECTORY/scripts
export KD_APPLICATIONS_DIRECTORY=$KD_PROJECT_ROOT_DIRECTORY/applications

export KD_APPLICATION_SCRIPTS_DIRECTORY=$KD_SCRIPTS_DIRECTORY/application





if [ ! -z "$KD_TARGET_APPLICATION_NAME" ]
then
      export KD_TARGET_APPLICATION_DIRECTORY=$KD_APPLICATIONS_DIRECTORY/$KD_TARGET_APPLICATION_NAME

      export KD_TARGET_DOCKER_IMAGE=demokafka/$KD_TARGET_APPLICATION_NAME:$KD_TARGET_APPLICATION_VERSION
fi

