---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.env }}-demokafka-resources-zookeeper-deployment-1
spec:
  selector:
    matchLabels:
      app: {{ .Values.global.env }}-demokafka-resources-zookeeper-1
  template:
    metadata:
      labels:
        app: {{ .Values.global.env }}-demokafka-resources-zookeeper-1
    spec:
      containers:
      - name: {{ .Values.global.env }}-demokafka-resources-zoo1
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: {{ .Values.global.env }}-demokafka-resources-zoo1
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.env }}-demokafka-resources-zoo1
  labels:
    app: {{ .Values.global.env }}-demokafka-resources-zookeeper-1
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: {{ .Values.global.env }}-demokafka-resources-zookeeper-1

